tasks:
  - init: pip install -r requirements.txt
    command: |
              cd MTTAPI
              uvicorn main:app --reload
  - init: npm install -g npm && cd MTTFront-End && npm install
    command: |
              cd MTTFront-End
              npm install -g @angular/cli
              ng serve